### ISSUE TITLE
I am not able to run the test.

### ISSUE THREAD

**Issue by pf64** [yanyongluan/MINNs#1]
Hi, I was very happy to see your code after I read the paper. So I installed keras with conda and I downloaded your code. 
However, it stopped saying:

/home/fariselli/miniconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "MI_Net.py", line 13, in <module>
    from mil_nets.dataset import load_dataset
  File "/home/fariselli/MINNs/mil_nets/__init__.py", line 6, in <module>
    from . import layer
  File "/home/fariselli/MINNs/mil_nets/layer.py", line 5, in <module>
    from keras import initializations
ImportError: cannot import name initializations

so I changed the code as:

from keras import initializers as initializations
#from keras import initializations

However, I obtained a second problem

Called with args:
Namespace(dataset='musk1', init_lr=0.0005, max_epoch=50, momentum=0.9, pooling_mode='max', weight_decay=0.005)
run= 0   fold= 0
Using TensorFlow backend.
/home/fariselli/miniconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
MI_Net.py:129: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(256, activation="relu", kernel_regularizer=<keras.reg...)`
  fc1 = Dense(256, activation='relu', W_regularizer=l2(args.weight_decay))(data_input)

Can you help me with it?
Thanks
Piero

**Comment by pf64** [comment]
I am sorry, but I pasted only half of the message. The whole message is this:

Called with args:
Namespace(dataset='musk1', init_lr=0.0005, max_epoch=50, momentum=0.9, pooling_mode='max', weight_decay=0.005)
run= 0   fold= 0
Using TensorFlow backend.
/home/fariselli/miniconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
MI_Net.py:129: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(256, activation="relu", kernel_regularizer=<keras.reg...)`
  fc1 = Dense(256, activation='relu', W_regularizer=l2(args.weight_decay))(data_input)
MI_Net.py:130: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(128, activation="relu", kernel_regularizer=<keras.reg...)`
  fc2 = Dense(128, activation='relu', W_regularizer=l2(args.weight_decay))(fc1)
MI_Net.py:131: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(64, activation="relu", kernel_regularizer=<keras.reg...)`
  fc3 = Dense(64, activation='relu', W_regularizer=l2(args.weight_decay))(fc2)
MI_Net.py:134: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.5)`
  dropout = Dropout(p=0.5)(fc3)
Traceback (most recent call last):
  File "MI_Net.py", line 171, in <module>
    acc[irun][ifold] = MI_Net(dataset[irun])
  File "MI_Net.py", line 137, in MI_Net
    fp = Feature_pooling(output_dim=1, W_regularizer=l2(args.weight_decay), pooling_mode=args.pooling_mode, name='fp')(dropout)
  File "/home/fariselli/miniconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 528, in __call__
    self.build(input_shapes[0])
  File "/home/fariselli/MINNs/mil_nets/layer.py", line 87, in build
    self.W = self.init((input_dim, self.output_dim), name='{}_W'.format(self.name))
TypeError: __call__() got an unexpected keyword argument 'name'

**Comment by yanyongluan** [comment]
Sorry for reply so late. Because I write this code one year before, and the latest Keras version is updated to   version '2.0' (API has large change). I may have time to change my code based on newest Keras version, or submit tensorflow implement, recently.

**Comment by yanyongluan** [comment]
I have pushed code for the latest Keras version.

**Comment by pf64** [comment]
Thanks! I downloaded it. As soon as I can I'll test it.
Thanks
